name: Generate Bug Fix Report

on:
  push:
    branches:
      - main

jobs:
  generate-report:
    name: Generate Bug Fix Report
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3  #checkout code

      # Step 2: Extract Bug Fix Commit Messages
      - name: Extract Bug Fix Commits
        id: extract_commits
        run: |
          echo "Extracting bug fix commits..."
          # Get all commits with keywords 'fix' or 'bugfix' since the last tag or commit
          git log --pretty=format:"%h %s" --grep='fix\\|bugfix' > bugfix_commits.txt

      # Step 3: Generate Markdown Document
      - name: Generate Bug Fix Report
        id: generate_report
        run: |
          echo "# Bug Fix Report" > bugfix_report.md
          echo "\n## Fixed Bugs" >> bugfix_report.md
          echo "\n| Commit Hash | Commit Message |" >> bugfix_report.md
          echo "|-------------|----------------|" >> bugfix_report.md
          while read -r line; do
            COMMIT_HASH=$(echo "$line" | awk '{print $1}')
            COMMIT_MESSAGE=$(echo "$line" | cut -d' ' -f2-)
            echo "| $COMMIT_HASH | $COMMIT_MESSAGE |" >> bugfix_report.md
          done < bugfix_commits.txt

      # Step 4: Commit and Push the Report
      - name: Commit and Push Report
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add Bug Fix Report"
          file_pattern: bugfix_report.md
          branch: main
